# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-03 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'verbose_name_plural': 'Estaciones'},
        ),
        migrations.AlterModelOptions(
            name='puntoventadispositivo',
            options={'verbose_name': 'Dispositivos Punto de Venta'},
        ),
        migrations.AddField(
            model_name='jornada',
            name='dia',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estacion',
            name='numero',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='serial',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='puntoventadispositivo',
            name='numero',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='puntoventadispositivo',
            name='serial',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
