# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-18 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20180503_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
            preserve_default=False,
        ),
    ]
