# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-21 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_jornada_diferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatcoCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('banco', models.CharField(choices=[('mercantil', 'Banco Mercantil'), ('provincial', 'Banco Provincial')], default='mercantil', max_length=50)),
                ('archivo', models.FileField(blank=True, default='', upload_to='csv-platco/')),
            ],
            options={
                'verbose_name': 'Archivos CSV Platco',
            },
        ),
    ]
