# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-22 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import ventas.models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_platcocsv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platcocsv',
            options={'verbose_name_plural': 'Archivos CSV Platco'},
        ),
        migrations.AlterField(
            model_name='platcocsv',
            name='archivo',
            field=models.FileField(blank=True, default='', upload_to=ventas.models.csv_directory_path),
        ),
        migrations.AlterField(
            model_name='platcocsv',
            name='banco',
            field=models.CharField(choices=[('Mercantil', 'Banco Mercantil'), ('Provincial', 'Banco Provincial')], default='mercantil', max_length=50),
        ),
    ]
