# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reporte',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
