# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20180423_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='icono',
            field=models.CharField(default='chrome_reader_mode', max_length=100),
        ),
    ]
