# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('reportes', models.ManyToManyField(to='articulos.Reporte')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_usuario',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='usuarios.TipoUsuario'),
            preserve_default=False,
        ),
    ]
