# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20180422_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='reportes',
            field=models.ManyToManyField(blank=True, to='articulos.Reporte'),
        ),
    ]
