# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-05 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('StorageQuantity', models.FloatField(default=0.0)),
                ('CostPrice', models.FloatField(default=0.0)),
                ('PackageQuantity', models.FloatField(default=1000, help_text='Monto para realizar el calculo del precio del gr del articulo (CostPrice)/(PackageQuantity)')),
                ('PercentageProfit', models.IntegerField(default=50)),
                ('SellPrice', models.FloatField(default=0)),
            ],
        ),
    ]
