# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-05 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celestes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='CostPrice',
            new_name='costPrice',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='PackageQuantity',
            new_name='packageQuantity',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='PercentageProfit',
            new_name='percentageProfit',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='SellPrice',
            new_name='sellPrice',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='StorageQuantity',
            new_name='storageQuantity',
        ),
    ]
