# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-05 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestes', '0002_auto_20200305_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='costPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='article',
            name='packageQuantity',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Monto para realizar el calculo del precio del gr del articulo (CostPrice)/(PackageQuantity)', max_digits=11),
        ),
        migrations.AlterField(
            model_name='article',
            name='sellPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='article',
            name='storageQuantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
