# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-05 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celestes', '0003_auto_20200305_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(default='+', help_text='"+" para sumar | "-" para restar', max_length=1)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celestes.Article')),
            ],
        ),
        migrations.CreateModel(
            name='MovementReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='movementarticle',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celestes.MovementReason'),
        ),
    ]
