# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-05 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestes', '0005_auto_20200305_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='_article_ingredients_+', to='celestes.Article'),
        ),
    ]
