# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celestes', '0006_auto_20200305_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pointBased', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('currencyBased', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='celestes.Currency')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='secondaryPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AddField(
            model_name='configuration',
            name='primaryCurrency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celestes.Currency'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='secondaryCurrency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_currency', to='celestes.Currency'),
        ),
    ]
