# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-05 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celestes', '0007_auto_20200305_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='article',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='article_ingredient', to='celestes.Ingredient'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celestes.Article'),
        ),
    ]
