# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-06 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestes', '0009_configuration_roundpriceby'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='taxPercentage',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=6),
        ),
    ]
