# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestes', '0010_configuration_taxpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='barcode',
            field=models.CharField(blank=True, help_text='Codigo usado para conectarse a leonux y hacer cambios al articulo', max_length=30, null=True),
        ),
    ]
