# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-06 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestes', '0011_article_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isForSell',
            field=models.BooleanField(default=False, help_text='El Articulo es para la venta?'),
        ),
    ]
