# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-27 15:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestes', '0013_movementarticle_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('movements', models.ManyToManyField(blank=True, to='celestes.MovementArticle')),
            ],
        ),
    ]
