# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-31 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celestes', '0014_documentmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cookingTime',
            field=models.IntegerField(blank=True, default=0, help_text='Tiempo de coccion en segundos'),
        ),
    ]
