# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-31 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celestes', '0016_articletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='celestes.ArticleType'),
        ),
    ]
